export const GET_USER_ROLE = "GET_USER_ROLE";
export const ADD_USER_ROLE = "ADD_USER_ROLE";
export const DELETE_USER_ROLE = "DELETE_USER_ROLE";

export const GET_LEAVE_HISTORY = "GET_LEAVE_HISTORY";

export const GET_REQUEST_LEAVE = "GET_REQUEST_LEAVE";
